### ISSUE TITLE
logic not correct for exercise one of grid layout

### ISSUE THREAD

**Issue by rcamach7** [TheOdinProject/css-exercises#120]
[Link To exercise](https://github.com/TheOdinProject/css-exercises/tree/main/grid/01-grid-layout-1) 
I believe logic should be reversed for the highlighted / boxed self check item below:
![css_grid](https://user-images.githubusercontent.com/20146375/151106121-2feecd66-18e1-49b1-86c0-0a32f90b6e8f.png)

It should be something along the lines of

**- The second column is three times larger than the first**

The solution provided also aligns with the second column being three times larger than the first column.

**Comment by LPRegen** [comment]
Can I take this of @thatblindgeye ? Obviously if @rcamach7 isn't going to do it.

**Comment by thatblindgeye** [comment]
Thank you for wanting to take this on, @LPRegen ! Unfortunately it looks like a PR is already open for this issue.

**Comment by thatblindgeye** [comment]
Update: @LPRegen due to some confusion this issue is open again. I have assigned you if you would like to work on it.

**Comment by thatblindgeye** [comment]
This has been resolved in PR #128
