### ISSUE TITLE
Foundations > 02-class-id-selectors: "DejaVu Sans" should be in quotes

### ISSUE THREAD

**Issue by MasQueElite** [TheOdinProject/css-exercises#132]
At `solution.css`:
> ```css
> .odd {
>   background-color: rgb(255, 167, 167);
>   --> font-family: Verdana, DejaVu Sans, sans-serif; <--
> }
> ```
*font-family: Verdana, DejaVu Sans, sans-serif;* should be *font-family: Verdana, **"DejaVu Sans"**, sans-serif;*

**Comment by ItsAndreWright** [comment]
I'd like to make this fix if it hasn't been assigned

**Comment by Rutvik5999** [comment]
Hello I want to fix this and i sure i'm fix this properly

**Comment by Maheshkumar-novice** [comment]
I've noticed this too. I was going to create a new issue but I saw this is already an issue here. This definitely needs a fix and somebody needs to fix it.

**Comment by thatblindgeye** [comment]
Apologies for the delay in reply, everyone. @scheals since you first asked, please let me know if you want to still work on this. Otherwise I will move down the list of who else has replied.
