### ISSUE TITLE
05 flex modal: solution files do not match desired outcome

### ISSUE THREAD

**Issue by nourHalhoul** [TheOdinProject/css-exercises#133]
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/thatblindgeye/css-exercises/blob/main/CONTRIBUTING.md)
- [x] The title of this issue is similar to the `file, exercise/lesson, or folder: brief description of bug` format, e.g. `01 flex center: solution files do not match desired outcome

- [ ] If approved, I would like to be assigned this issue to work on it

**1. Description of the Bug**
The provided .css solution file does not match the necessary outcome.
![Capture](https://user-images.githubusercontent.com/90423960/152611405-d5e71603-75bb-4b25-9c3d-2d5eb0810b7c.png)

**2. How To Reproduce**
Copy and paste the .css and .html file within the solutions folder, and launch the respective index.html file.

**3. Expected Behavior**
The expected outcome is listed and displayed within the README.md file in the 05-flex-modal folder.

**4. Desktop/Device:**
 - Device: Desktop
 - OS: Xubuntu
 - Browser: Chrome

**Comment by xandora** [comment]
Seems OK to me through VSCode Live Preview:
![image](https://user-images.githubusercontent.com/2021268/152613005-4561556c-ed71-4c88-b831-556522d1571b.png)

As well as through Chrome and Firefox:
![image](https://user-images.githubusercontent.com/2021268/152613125-48df3ba8-bb11-435e-b252-f0de943e3b4d.png)

**Comment by nourHalhoul** [comment]
I spent hours trying to figure out what was wrong with my code. Turns out, I closed my container right after the "close-button" element, instead of the "cancel" element.
I need to take a break.
