### ISSUE TITLE
CSS Foundations Exercise 05-descendant-combinator: Add full solution

### ISSUE THREAD

**Issue by Micosaur** [TheOdinProject/css-exercises#153]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Add full descendant combinator solution for this exercise to let us see the possibilities which we may have never thought of.

File Path: css-exercises>foundations>05-descendant-combinator>solution>solutions.css

**2. Acceptance Criteria:**

- [ ] Add to solutions.css file either by css comment or by code.

```
/* Other possible combinations of selectors

div p
div .text
.container p

*/
```
or 

```
div p {
  background-color: yellow;
  color: red;
  font-size: 20px;
  text-align: center;
}

div .text {
  background-color: yellow;
  color: red;
  font-size: 20px;
  text-align: center;
}

.container p {
  background-color: yellow;
  color: red;
  font-size: 20px;
  text-align: center;
}
```

**Comment by thatblindgeye** [comment]
This I believe could be good to add in as a commented out part, though the first option would be much better than needlessly repeating all of the styles.

I've assigned you. Just an FYI, you shouldn't complete the checkboxes for the Acceptance Criteria ahead of time; those can be completed as each item is completed.

**Comment by Micosaur** [comment]
> This I believe could be good to add in as a commented out part, though the first option would be much better than needlessly repeating all of the styles.
> 
> I've assigned you. Just an FYI, you shouldn't complete the checkboxes for the Acceptance Criteria ahead of time; those can be completed as each item is completed.

Gotcha
