### ISSUE TITLE
flex/06-flex-layout: Add a working link to href

### ISSUE THREAD

**Issue by Micosaur** [TheOdinProject/css-exercises#154]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Either add a working url link to href in html files or assign it as a task for the exercise. As of now, all (8) links leads you to a "Your file couldn’t be accessed" webpage.

**2. Acceptance Criteria:**

[x] Add href="#" to every anchor.
or
[x] Add the full url of "http://www.google.com" webpage (which seemed to be the original intention as the href was initially "google.com""
or
[x] Make it a task in the assignment 
```
-Fix the url to make the page redirect to google
or
-Fix the url to redirect to the same page.
```

**3. Additional Information:**

Currently
<img width="152" alt="Screen Shot 2022-03-16 at 7 08 36 PM" src="https://user-images.githubusercontent.com/70674855/158722378-a0a47b56-b511-4c30-8814-e0e4f2e9f63a.png">

**Comment by thatblindgeye** [comment]
I don't believe this is worth updating for. The purpose of the exercises isn't to have or add working links, but to practice using Flex properties.

**Comment by Micosaur** [comment]
I hope you can reconsider. I believe that it is important to be consistent whenever seeing or using anchors/href by adding protocols (http) for urls. Consistency is key, especially for beginners. If not, I understand and will be closing both issues after getting your reply (or you can close it too).

**Comment by thatblindgeye** [comment]
Ultimately I won't block the update so I can assign you. I would lump the updates for both issues in one PR, though. Either the first or second option should be done, as it definitely shouldn't be a part of the exercise instructions.
