### ISSUE TITLE
flex/07-flex-layout-2: Add a working link to href

### ISSUE THREAD

**Issue by Micosaur** [TheOdinProject/css-exercises#155]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Just like the broken links in exercise 06. As of now, all (4) links leads you to a "Cannot GET /flex/07-flex-layout-2/solution/google.com" webpage. Requesting to make the links "work" (or not lead to an error page).

**2. Acceptance Criteria:**

**Possible solutions:**

[x] Add href="#" to every anchor.
or
[x] Add the full url of "http://www.google.com/" webpage (which seemed to be the original intention as the href was initially "google.com""
or
[x] Make it a task in the assignment

```
-Fix the url to make the page redirect to google
or
-Fix the url to redirect to the same page.
```

**3. Additional Information:**

Currently 
<img width="152" alt="158722378-a0a47b56-b511-4c30-8814-e0e4f2e9f63a" src="https://user-images.githubusercontent.com/70674855/158898427-c109c3fe-d241-4e30-8d9b-dfad576b5b38.png">

**Comment by thatblindgeye** [comment]
See #154 for context
