### ISSUE TITLE
Bug - : chaining selectors - images won't load in the given index.html file

### ISSUE THREAD

**Issue by kkoullapis** [TheOdinProject/css-exercises#197]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Images won't load. I believe its because the pexels reference no longer works.

**2. How To Reproduce:**
 Try to load index.html in the chaining selectors exercise

**3. Expected Behavior:**
 Images won't load

**4. Desktop/Device:**

-   Device:  Laptop
-   OS:  Linux
-   Browser:  Chrome
-   Version:  103

**5. Additional Information:**

**Comment by dm-murphy** [comment]
Hi @kkoullapis 👋 

I am not having any issues loading the `index.html` of the 04-chaining-selectors exercise. Are you still experiencing this issue and can you give any more details on your process for trying to open it? Thanks!

**Comment by gogoiakash2311** [comment]
Hey! @kkoullapis 
Download the images from the repo.

**Comment by gogoiakash2311** [comment]
hey! @kkoullapis 
Download the images from the repo and try to change the image format to png. it will work.

**Comment by thatblindgeye** [comment]
@kkoullapis Are you still having issues with the images?

**Comment by codyloyd** [comment]
closing this issue.. cant' replicate, and haven't had a response for quite some time.
