### ISSUE TITLE
Suggest to include a step to FORK before cloning

### ISSUE THREAD

**Issue by kyyeo** [TheOdinProject/css-exercises#21]
Hello TOP, thanks for this content. It helps solidify understanding. 

However, can I suggest a minor update to README.md? It is best to specify that learners go to the top-right in Github, click `Fork`, before cloning. 

Otherwise, learners (like myself) would face the following hint when trying to commit to their own GitHub repo `adding embedded git repository`

**Comment by Mogashni** [comment]
I agree with adding how to do the fork step in the README.md

**Comment by codyloyd** [comment]
done! thanks
