### ISSUE TITLE
Bug - Flex exercises: readme missing requirements in the 06-flex-layout solution

### ISSUE THREAD

**Issue by DaveIsntFunny** [TheOdinProject/css-exercises#215]
Complete the following REQUIRED checkboxes:
-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The readme gives no hint or self-check for the "content" class flex elements leading to a simple "text-align: center;" fulfilling the basic criteria.

**2. How To Reproduce:**

Following hint and self-check in the readme.md in 06-flex-layout, add "text-align: center;" to content class to match the desired-outcome.png.  Compare to solution.css which uses five flex elements to accomplish this but also fulfills and **unlisted requirement** to shrink the content as the browser window is resized.

**3. Expected Behavior:**

Following hint and self-check in the readme.md in 06-flex-layout, **add flex elements** to content class to match the desired-outcome.png.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

Add hints and/or self-check items to the readme so that users know to add flex elements instead of the simpler text-align element.

**Comment by DaveIsntFunny** [comment]
Ok, I looked at it again and the solution doesn't do anything that "text-align: center;" does.  It's just going everything the hard way apparently?

**Comment by anujpandeyin** [comment]
.

**Comment by thatblindgeye** [comment]
> Ok, I looked at it again and the solution doesn't do anything that "text-align: center;" doesn't. It's just going everything the hard way apparently?

The purposes of the exercises are to utilize flex. While there may be simpler ways to get the same result, those ways won't help with practicing with flex properties.

We could possibly add a bullet to the self check that "Everything should be styled with flex", but at this point it should be clear that users should be utilizing flex to position things.
