### ISSUE TITLE
Bug - foundations/01-css-methods/solutions : Solution does not represent desired outcome

### ISSUE THREAD

**Issue by martinhavens** [TheOdinProject/css-exercises#216]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

![image](https://user-images.githubusercontent.com/77357736/185751788-81e05506-4cb1-40ac-b862-1e2419d0cdeb.png)

**2. How To Reproduce:**
What steps one might need to take in order to reproduce this bug, e.g.:
1. Move solution.html and solution.css into a folder and launch the html page.
2. Be confused because your test window is maximized and shows the background extending across the entire page
3. Realize after looking up "how to reduce background color width" that the screenshot is in a smaller window.
To a new user, the top image does not replicate the bottom and causes frustration.
![image](https://user-images.githubusercontent.com/77357736/185751925-289a7ee6-7e6c-4093-9500-6e82fd174775.png)
![image](https://user-images.githubusercontent.com/77357736/185751937-d4a46120-87a9-4389-bce0-76fad29137c8.png) 

**3. Expected Behavior:**
1. See the expected outcome does not have to be exactly bordering the text, for the external case
2. If a user has an expanded window, the red border will be much larger than as is shown

**4. Desktop/Device:**
The more information you are able to provide, the better.
-   Device: PC
-   OS: W11
-   Browser: Firefox
-   Version: 103.0.2

**5. Additional Information:**
We should replace the desired outcome picture of 
![image](https://user-images.githubusercontent.com/77357736/185752082-71ca7a20-ebf2-4539-a37c-aad2a1d8c50e.png)
with one that a more inexperienced user might come across: 
![image](https://user-images.githubusercontent.com/77357736/185751925-289a7ee6-7e6c-4093-9500-6e82fd174775.png)

**Comment by ev0clu** [comment]
Agree, it is still open.
