### ISSUE TITLE
Want to add Cheatsheet 

### ISSUE THREAD

**Issue by dazzle-sah** [TheOdinProject/css-exercises#235]
Complete the following REQUIRED checkboxes:

[ Yes ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
[ Yes] The title of this issue follows the location for request: brief description of request format, e.g. Foundations exercises: Add exercise for XYZ
The following checkbox is OPTIONAL:

[ Yes ] I would like to be assigned this issue to work on it
1. Description of the Feature Request:
I want to add cheasheet and short before-hand codes for solving these exercises, such that the codes are on the fingertips of the coder.

2. Acceptance Criteria:
A folder will be added
Containing Links ns shorcut tricks of css

3. Additional Information:

**Comment by ChargrilledChook** [comment]
Thank you for the suggestion but the exercises are intended to be done alongside the curriculum content, which is sufficient reference
