### ISSUE TITLE
Animations: Add CSS Checkbox Styles

### ISSUE THREAD

**Issue by shreyash2610** [TheOdinProject/css-exercises#240]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by kritika902** [comment]
plz assign it to me

**Comment by ChargrilledChook** [comment]
Please provide more detail if this is a feature request, I'm a little unsure what you're asking.
