### ISSUE TITLE
Bug - Flex modal exercise: Add missing solution comment

### ISSUE THREAD

**Issue by pjk2022** [TheOdinProject/css-exercises#248]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
The solution html for 05-flex-modal exercise is missing a comment that highlights that the div closing tag for the header was moved to create a container that encompasses both the header text and close-button div.

**2. How To Reproduce:**
1. Open flex/05-flex-modal/solution/solution.html
2. Review for non-existent comment re: adjusted closing div tag.

**3. Expected Behavior:**
1. There should be a comment in the solution.css that highlights that the closing header div tag needs to be moved to create a container that encompasses both the header text and close-button div in order for the flex properties to apply.

**5. Additional Information:**
There are two other closed issues that were trying to get at this issue, but framed it as the solution being incorrect.
This would also address much of the confusion also discussed in Discord, as users are stumped by the solution not working on their end.

It may also be worth clarifying the instructions in the READ.ME (the "edit the HTML a bit" sentence).
Thus far in the curriculum, we've be assuming/expecting the index.html to be "correct as is," so a bigger emphasis might need to  be placed on really reviewing that given index.html.

**Comment by Muhammad-Zulqarnain-Awan** [comment]
Will you assign this issue to me?

**Comment by pjk2022** [comment]
I don't have the ability to assign the issue -- a TOP admin/contributor will likely review this first and then assign you!

**Comment by kritika902** [comment]
assign it to me plz

**Comment by glutes83** [comment]
Yeah, I ran into this issue. I only figured out that to get the solution to work one has to remove that closing <div> tag, but I don't understand why it doesn't work if you don't do that. It would be **really** helpful for the solution to spend some time explaining this, because as far as I know so far in the curriculum, nothing has mentioned any reason why one would nest a div inside another div without closing the first div. How does that even work? Does the closing <div> tag for the container close the header, or the close-button? 

There's just so much confusion here with no explanation.

**Comment by thatblindgeye** [comment]
@Muhammad-Zulqarnain-Awan @kritika902 would either of you still want to work on this?

**Comment by Muhammad-Zulqarnain-Awan** [comment]
@thatblindgeye I am really sorry no.

**Comment by linglejack06** [comment]
I'll fix this issue

**Comment by thatblindgeye** [comment]
@linglejack06 you're assigned!
