### ISSUE TITLE
flex/03-flex-header-2: Solution can be simplified by using margin-left:auto to split navigation

### ISSUE THREAD

**Issue by c-auri** [TheOdinProject/css-exercises#250]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The exercise can be solved without modifying the markdown by using `margin-left: auto` to split the navigation, as introduced in the assigned readings for the lesson ([here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container#using_auto_margins_for_main_axis_alignment) and [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox#split_navigation)). This simplifies the solution and practices a concept that would otherwise remain untested (as far as I can tell).

**2. Acceptance Criteria:**

- [ ] `solution.css` applies `margin-left: auto` to the `notification` class.
- [ ] The markdown in `solution.html` does not add any containers.
- [ ] The introductory text about editing the markdown in the `README` is moved to the next exercise.
- [ ] [Optional] A hint that points towards the `auto` property is added to the `README`.

**3. Additional Information:**

My solution can be found [here](https://github.com/TheOdinProject/css-exercises/compare/main...c-auri:css-exercises:split-navigation).

**Comment by thatblindgeye** [comment]
I'm not sure if this would be an entirely necessary update. While it would slightly clean things up, it's using something that has only been mentioned in passing in one of the assigned readings, while the point of these exercises is to get practice with the various flex properties themselves.

**Comment by codyloyd** [comment]
I think this is not needed.  We've already stated in a few places that students do not need to solve things in the exact same way as the solution file.. so if someone thinks of doing the margin:auto trick.. that's fine.

We don't need to update the official solution just for that.
