### ISSUE TITLE
Bug - Foundations 03 - Grouping Selectors: Wrong font style used for desired outcome image

### ISSUE THREAD

**Issue by l33tzke** [TheOdinProject/css-exercises#259]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
On the README, the image presented as "desired outcome" uses Times New Roman for the button texts, whereas the description of the exercise specifies Helvetica as the first font in the list, which has higher precedence and will in most cases be used.

**2. How To Reproduce:**
Open README.md, or check the desired-outcome.png 

**3. Expected Behavior:**
The image should look like this:
![image](https://user-images.githubusercontent.com/355407/204387837-fed5c5e7-a1bd-455c-b281-c2388fa15517.png)

**4. Desktop/Device:**
Should be reproducible under any setup.

**5. Additional Information:**
Simple mismatch between expectation and actual exercise outcome, nothing that stops the progress.

**Comment by Shubham1450** [comment]
I can work on this issue assign this to me.

**Comment by arinze19** [comment]
@Shubham1450 are you still working on this issue? 
If so please open up a PR as this issue seems to come up quite often on discord
