### ISSUE TITLE
Bug - flex/07-flex-layout-2: README.md and solution.css inconsistency (Holy Grail)

### ISSUE THREAD

**Issue by latsonj** [TheOdinProject/css-exercises#269]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

README.md states the sidebar should be 300px wide (Line 29). When opening solution.html file in browser and inspecting the sidebar, it is 332px wide. solution.css does not include:
```
.sidebar {
box-sizing: border-box;

*other style declarations*
}
```
If this isn't intended then box-sizing should be included in the solution.

![sidebar](https://user-images.githubusercontent.com/116848884/209049560-86c58787-406c-4ae0-83bd-bbfe02edc596.png)

**2. How To Reproduce:**

1. Open solution.html file in browser
2. Inspect sidebar element (332px)

**3. Expected Behavior:**

1. Open solution.html file in brower
2. Inspect sidebar element (300px)
3. solution.css file includes box-sizing declaration under sidebar class

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by dotarjun** [comment]
Can this issue be assigned to me

**Comment by xandora** [comment]
> Can this issue be assigned to me

All yours. I had a look at the code myself, and can see what the problem likely is. Will be interesting to see your solution.
