### ISSUE TITLE
CSS Exercises: Add an Eslint config for the repo

### ISSUE THREAD

**Issue by dotarjun** [TheOdinProject/css-exercises#282]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Add an Eslint config for the repo which would maintain code style across all PRs and prevent inconsistencies in formatting 

**2. Acceptance Criteria:**

- [ ] ``.eslintrc`` file 

**3. Additional Information:**

Not clear whether  ``.eslintrc`` should be the one in Airbnb or custom according to the way currently noticed across the repo. Need input from a maintainer regarding this.

**Comment by codyloyd** [comment]
I am not against this idea.. but I also don't think it's particularly necessary.  Most changes that are made to this repo are small typo fixes and tweaks.  There is not any large amount of development work happening here.

HOWEVER: having it wouldn't _hurt_ anything.. so if someone wanted to do the work, I'd be inclined to go ahead and approve it.

I'm curious what the rest of the maintainers think. @TheOdinProject/foundations @TheOdinProject/intermediate-html-css

**Comment by thatblindgeye** [comment]
Pretty much agree with the above. I don't think we need it, but if someone were to put up a PR I wouldn't block it.

**Comment by wise-king-sullyman** [comment]
+1 on the previous statements.

**Comment by codyloyd** [comment]
@dotarjun go for it, if you want. 😄

**Comment by bEluga0000** [comment]
can some one explain what is the one more task which is not done in this issue

**Comment by dotarjun** [comment]
great work beluga, I've been pretty busy so I unassigned myself from this issue

**Comment by codyloyd** [comment]
As this is very low priority, I am going to go ahead and close this issue for now.
