### ISSUE TITLE
Text contrasts poorly in holy grail layout with grid example -article section 

### ISSUE THREAD

**Issue by winniebosy** [TheOdinProject/css-exercises#286]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the example, the text contrasts poorly with the background color making reading difficult for learners with low vision and color blindness.  Setting the background color to achieve at least a ratio of 4.5: 1 would improve the readability for learners with low vision and color blindness.

**2. Acceptance Criteria:**

For example, set the background color to #174480 (a 9.66 ratio) to make the example readable.

**3. Additional Information:**

![Screenshot of the holy grail grid layout article section ](https://user-images.githubusercontent.com/40880690/216911108-08925e9b-29ed-4c58-869f-29483e2eab00.png)

**Comment by winniebosy** [comment]
Thank you @KevinMulhern

**Comment by CouchofTomato** [comment]
@winniebosy Do you want us to assign this issue to you to work on?

**Comment by codyloyd** [comment]
@winniebosy gets it first, since they reported it.

But if they do not want it, or do not reply here shortly, we can assign it to you, @christinamakes .

**Comment by winniebosy** [comment]
@codyloyd I have no problem with @christinamakes working on the issue.

**Comment by christinamakes** [comment]
Also just to make sure I have you right, I should close out all three and make a new PR to encompass all the changes? Is that right?
@CouchofTomato

**Comment by codyloyd** [comment]
@christinamakes I hesitate to just invent more work for you... but it might be helpful if you just comb through everything with an eye for color contrast.

As far as I know, everything has an image in the README, so it shouldn't take tooooo long.

I _suspect_ that #324 is talking about the same yellow background that you brought up.  Let me know if that doesn't seem feasible since it _is_ more work than you specifically signed up for.

**Comment by christinamakes** [comment]
@codyloyd @CouchofTomato I will be completing work on all three this weekend, as well as combing through the rest of the exercises.

I'm just like to clarify how I should handle these for metrics purposes. Would it be better if I closed each individually as the work is completed or close all three and complete work on a new issue? Thanks

**Comment by codyloyd** [comment]
dont' worry about the issues too much.. just do one PR and we'll mark them all closed at the same time when we merge the PR.
