### ISSUE TITLE
Confusion between type and class name. 

### ISSUE THREAD

**Issue by pratikthorat8** [TheOdinProject/css-exercises#31]
![Github Issue](https://user-images.githubusercontent.com/46789011/134937487-57c277a9-afac-48ac-80de-9cf55ba441ce.JPG)
In CSS exercise margin and padding 2 section, It will better if we use a different class name. Seems trivial but I was confused while styling the third div in this assignment. It will be better if the class name would be changed to something like container. or sub__container (I use BEM case when writing class names but it's not necessary. ) Please do look into it as it may save many students like us some time.

**Comment by codyloyd** [comment]
this is a fine suggestion.  will fix.
