### ISSUE TITLE
Bug - : css-exercises/foundations/04-chaining-selectors /README.md : link down in first line.

### ISSUE THREAD

**Issue by ssff1293** [TheOdinProject/css-exercises#341]
Complete the following REQUIRED checkboxes:
-   [ x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ x ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ x ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the first line, "Credits for the images in this exercise go to [Katho Mutodo](https://www.pexels.com/@photobykatho?utm_content=attributionCopyText&utm_medium=referral&utm_source=pexels) and [Andrea Piacquadio](https://www.pexels.com/@olly?utm_content=attributionCopyText&utm_medium=referral&utm_source=pexels)."
the Katho Mutodo link is down.

**2. How To Reproduce:**

I read the exercise and follow the link.

**3. Expected Behavior:**

Should take to bio web-page of the artist, just like the other link(Andra Piacquadio).

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

the Pexels account of Kathu Mutodo has been deleted of pexels...

i suggest > https://linktr.ee/photobykatho_

**Comment by ssff1293** [comment]
im thinking i can just make a PR for this case, right?

**Comment by CouchofTomato** [comment]
The link you provided doesn't seem to go anywhere?

**Comment by Asartea** [comment]
I think they meant [https://linktr.ee/photobykatho_](https://linktr.ee/photobykatho_) (GitHub seems to drop the last underscore)

**Comment by ssff1293** [comment]
[Katho Mutodo](https://linktr.ee/photobykatho_)

**Comment by CouchofTomato** [comment]
Yeah then you can just make a PR if you want to update a link
