### ISSUE TITLE
Easy Fix - flex: 06-flex-layout: README.md self check appears to be inconsistent with solution.css

### ISSUE THREAD

**Issue by SupraSensum** [TheOdinProject/css-exercises#349]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Last list item under the "Self Check" section of README.md says "There is space between the logo, input and buttons", but the related solution.css only gives space between the input and buttons via "margin-bottom: 16px;" applied to .input

Space is visible between logo and input, but only because the image file itself has some space at the bottom after "THE ODIN PROJECT" text.

Proposed solutions:

1. Remove "logo" from the last self check item in README.md so it instead reads, "There is space between the input and buttons."
2. Add a "margin-bottom: 16px;" to the img element above .input in solution.css

I'm excited and a bit nervous about my first issue ever! Hopefully I didn't overlook anything.

**Comment by thatblindgeye** [comment]
I think adding the space between the logo and input makes sense. I'll assign you @SupraSensum. I'm actually wondering whether we should even be using the margin on the `.input` or if we should e using the `gap` property on the `.content` element, since this *is* a Flex exercise.

Might be easier to add a margin, but if you'd want to test using the gap property instead feel free!

**Comment by SupraSensum** [comment]
Using gap

**Comment by SupraSensum** [comment]
GitHub won't allow me to create a second fork of css-exercises. Creating a PR from my current fork would bring in all other changes. I tried using `git cherry-pick <commit hash>`, but I figured I'd ask here first before complicating things further.

**Comment by thatblindgeye** [comment]
It depends what your local looks like. Using another branch would be useful here.
