### ISSUE TITLE
Grammar in the README.md file

### ISSUE THREAD

**Issue by housepanther** [TheOdinProject/css-exercises#358]
Greetings!

In the README.md file on line 8, the sentence, "Issues with the cascade can be the bane of their existence for many when it comes to CSS" should be changed to "Issues with the cascade can be the bane of the existence for many when it comes to CSS"

**Comment by ManonLef** [comment]
This applies to 'the many' and thus doesn't sound wrong to me. Just like mosquitos can be "the bane of my existence".
I will close this, but feel free to open a PR if you feel strongly about this or think I'm incorrect, since English is not my first language.
