### ISSUE TITLE
Bug - :

### ISSUE THREAD

**Issue by tushar-raven** [TheOdinProject/css-exercises#363]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There is an extra line of code in the solution of the "pop-up" exercise under the animation section.
<img width="486" alt="Screenshot 2023-08-18 at 8 10 52 PM" src="https://github.com/TheOdinProject/css-exercises/assets/72013857/23ee162f-6897-4fdb-b4b6-3c326de450a5">

**2. How To Reproduce:**

Visit css-exercises/animation/pop-up/solution/solution.js

**3. Expected Behavior:**

The code doesn't do anything.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

 OS

**5. Additional Information:**

**Comment by wise-king-sullyman** [comment]
Seems like it's not needed to me as well, thanks for reporting, assigned!

**Comment by tushar-raven** [comment]
I think the guy was trying to set "closing by clicking on the backdrop" but it didn't work.

**Comment by ManonLef** [comment]
@tushar-raven you have been assigned this issue a few weeks back. Are you still willing to work on this?

**Comment by tushar-raven** [comment]
I am sorry, I didn't know it was assigned to me. I will work on it.

Thanks!

**Comment by ManonLef** [comment]
No problem, I thought as much and hence the reminder! Thank you for doing this

**Comment by fabulousgk** [comment]
I will take this.

**Comment by MaoShizhong** [comment]
Well that was freaky timing just as I look at this issue :fearful: 

Assigned you, @fabulousgk

**Comment by fabulousgk** [comment]
Haha, I came here to open an issue, and saw this one just hanging around.
