### ISSUE TITLE
Improve Documentation for CSS Exercises

### ISSUE THREAD

**Issue by MehakMantri** [TheOdinProject/css-exercises#417]
Issue Description:
Enhance the CSS exercise documentation by providing clear introductions, exercise descriptions, setup instructions, coding guidelines, visual examples, self-checklists, and contribution guidelines. Make sure the documentation is well-structured and user-friendly to aid learners and contributors.

Suggested Improvements:
Introduction and Purpose
Prerequisites
Coding Guidelines
Visual Examples
Self-Checklists
Hints and Tips
GitHub Repository Links
FAQ Section
This enhanced documentation will provide a more comprehensive and user-friendly guide for learners, making it easier for them to understand and navigate the CSS exercises.

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by thatblindgeye** [comment]
Gonna close this out as between the repo's README and each exercise's individual README, I'm not sure there's really much else to expand on that we don't already cover.
