### ISSUE TITLE
flex/06-flex-layout: Improvement to mobile layout in solution

### ISSUE THREAD

**Issue by jwsoh07** [TheOdinProject/css-exercises#435]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I would like to make things a little prettier in mobile view with a few lines of code change.
Current predefined CSS in solution.css (before solution portion) will yield a UI like this.

<img width="396" alt="image" src="https://github.com/TheOdinProject/css-exercises/assets/121473009/b6337e01-2058-4d60-81f6-c2e383f907c1">

**After CSS changes:**

<img width="393" alt="image" src="https://github.com/TheOdinProject/css-exercises/assets/121473009/0de91986-bffd-45df-839f-6ee659ced29b">

**2. Acceptance Criteria:**

**Comment by CouchofTomato** [comment]
@TheOdinProject/html-css 

Can someone take a look please

**Comment by codyloyd** [comment]
@jwsoh07 it depends greatly on what your changes are.  Can you share what you're proposing?

**Comment by jwsoh07** [comment]
@codyloyd hey again!

I only wanted to change 2 things.
1. The logo image to resize smaller in mobile view.
2. The text / search field to resize smaller in mobile view.

If you compare the 2 images above, you can see the size of the 2 mentioned items smaller in the 2nd image which looks a tad prettier.

**Comment by codyloyd** [comment]
We don't want to introduce media queries yet.. so I don't think we should worry about that on this one.

**Comment by jwsoh07** [comment]
I actually did it using a min-width property like so (in the image).

<img width="1309" alt="image" src="https://github.com/TheOdinProject/css-exercises/assets/121473009/912d0b4d-d539-426f-b183-db2373d88136">

**Comment by codyloyd** [comment]
I still think this is too advanced for students at this point.. almost none of them will come up with it on their own, and then they will be frustrated when they see it in the solution.

**Comment by jwsoh07** [comment]
@codyloyd okay, I got you. We can close this 🙂
