### ISSUE TITLE
Bug - 04-chaining-selectors : images don't exist in the index page

### ISSUE THREAD

**Issue by ghost** [TheOdinProject/css-exercises#448]
Complete the following REQUIRED checkboxes:
-   [ *] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ *] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

To complete this issue:

- Update the `index.html` file so that the image `src` attributes are pre-populated for the users, rather than requiring them to enter that info themselves
- Update the exercise README to remove the note regarding downloading the images and putting them in a folder

**Comment by learnerforlyf** [comment]
i am unable to download the images to complete the exercise on "04-chaining-selectors". pls help me in downloading the images

**Comment by fabulousgk** [comment]
> i am unable to download the images to complete the exercise on "04-chaining-selectors". pls help me in downloading the images

The images are part of the exercise, if you cloned the repository you already have them.

**Comment by thatblindgeye** [comment]
@fabulousgk that was a while ago, but I want to say my intent was for users to also practice linking images... It also could have just been something I wasn't thinking of at the time 😆 Can definitely see it being easier/better if we setup the image links for the user like you said, though. Will open up this to be taken on and update the initial comment with what needs to be done.

**Comment by fabulousgk** [comment]
If no one else wants to pick this up, I will do it

**Comment by jasonguf** [comment]
Good morning, can I be assigned to this issue? I have a pull request that contains the updated index.html file with the src attributes for the images, a new folder called "images" which contains the required images for the exercise, and the updated README.md file which doesn't contain the note that tells the user to download the images and to place them in the "images" folder.
