### ISSUE TITLE
Bug - Flexbox exercises:<a> tags linked to google.com don't go to google

### ISSUE THREAD

**Issue by ojuliocode** [TheOdinProject/css-exercises#453]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

There is a list of <a> links, that should be redirected to google.com. But the links are missing the https:// protocol, and it leads to a GET error (as it is redirecting to my own repo, on google.com)

**2. How To Reproduce:**

1. Visit the lesson page (flex/03-flex-header-2/index.html)
2. Click on any link

**3. Expected Behavior:**

1.After visiting the lesson (as in 2), by clicking any link you should be redirected to google.com

**4. Desktop/Device:**
**Didn't fill this info because it's a really simple bug, happens anywhere that i tested (motorola g10, windows and linux)**
Tested in Edge, Chrome and Safari

**5. Additional Information:**

**Comment by Adityaa-Singh07** [comment]
tags linked to google.com don't go to google #453
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flex Header 2</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="header">
      <div class="logo">
        LOGO
      </div>
      <ul class="links">
        <li><a href="https://www.google.com">link-one</a></li>
        <li><a href="https://www.google.com">link-two</a></li>
        <li><a href="https://www.google.com">link-three</a></li>
      </ul>
      <button class="notifications">
        1 new notification
      </button>
      <div class="profile-image"></div>
    </div>
  </body>
</html>

**Comment by thatblindgeye** [comment]
@ojuliocode while the purpose of the links isn't for them to be functional, I can see how it can still be confusing. I'll assign you if you'd still like to make this update. Would you mind also checking other instances we're using anchor tags in the CSS exercises?

**Comment by thatblindgeye** [comment]
@ojuliocode checking in if you'd still like to work on this

**Comment by ojuliocode** [comment]
Hi, sorry for the delay! Currently I dont think I would be able to work on this. When I posted the issue I was on vacations and looking for some open source to contribute. Now unfortenetly I don't think I could do this due to time

**Comment by ojuliocode** [comment]
Absolutely, sorry for the delay. Already made the pr
