### ISSUE TITLE
Bug - Flex exercises-02-flex-header: The font in the desired image doesn't match the solution font.

### ISSUE THREAD

**Issue by kesava-karri** [TheOdinProject/css-exercises#458]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- The font in the solution.html doesn't match the font in the image of desired output.
- This should be the img of desired output
   
<img width="1440" alt="image" src="https://github.com/TheOdinProject/css-exercises/assets/29258614/591f74a8-c140-4e75-9666-936e75661e31">

**2. How To Reproduce:**
- Open the solution.html in the browser

**3. Expected Behavior:**
- Match font with the solution or update the desired image.

**4. Desktop/Device:**

-   Device: Macbook M1
-   OS: macOS - Sonoma 14.2.1
-   Browser: chrome
-   Version: 120.0.6099.199

**5. Additional Information:**

- I was trying to match the font as well, which I feel would help for future TOP learners if asked not to be bothered with the font (at least in this exercise).

**Comment by Soonull** [comment]
**### Can you explain the problem further?** 
As I open the project, The desired image matches the solution.html output.
Either the problem is solved or I want a more detailed explaination. THANK YOU

**Comment by kesava-karri** [comment]
Hi @Soonull,

Thank you for addressing the font issue in this pull request.

I've been following the discussion on the related issue, and I believe there might be a slight misunderstanding. While I value the effort you put into this, I was already prepared to make the changes and had been awaiting confirmation from TOP before proceeding.

Looking forward to hearing your thoughts and those of the TOP representative. Thanks!

**Comment by Soonull** [comment]
Hello @kesava-karri 
Thank you for addressing me. Its surely a misunderstanding from my end. I assume you wanted to resolve this bug which mistakenly I did. I was starting out with Github Opensourceand thought this would be an easy project. If you want I can take back my pull request, no problem for me. 

Thank you

**Comment by kesava-karri** [comment]
Thank you for your prompt response and for your contribution! I appreciate your honesty about the misunderstanding. It's completely okay—we've all been there, especially when starting out with open source.

Given the context, I would kindly request you to retract your pull request. Since I'm relatively new to open source too.

Thanks again for your understanding.

**Comment by Soonull** [comment]
Sure 😄
