### ISSUE TITLE
README:  Clarify workflow with this repo

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/css-exercises#465]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The readme currently states:
>Do not submit your solutions to this repo, as any PRs that do so will be closed without merging.

We get questions seeking clarification of this on Discord fairly often.  I suggest we edit it to something like this:

>Go ahead and commit your changes and push them to your fork, but do not open a Pull Request to submit your changes to this repo.  Doing so creates extra work for our maintainers as the PR will simply be closed.

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by CouchofTomato** [comment]
If we're going to change this to offer up additoinal context we should probably explain why. Although we would like to avoid extra work, the reason we close them is because if we merged the PR's it would change the files for other students who forked the repo etc.

**Comment by fabulousgk** [comment]
Yeah, I would be good with that as well, I think it is a good educational opportunity

**Comment by fabulousgk** [comment]
Am I cleared to make this change?

**Comment by thatblindgeye** [comment]
We have a somewhat similar issue in our JS exercise repo. Whatever change is made here should be made in all our exercise repos. For context, the JS exercise issue: https://github.com/TheOdinProject/javascript-exercises/issues/380

I had mentioned moving the verbiage to the opening paragraph of the repo README, to make it more immediate of a disclaimer. @fabulousgk I'll assign you if you'd like to make the change in this repo, and we can keep this in mind for our other repos as well (the issue in our JS exercise repo may be assigned out to someone else).
