### ISSUE TITLE
Bug - Flex/07-flex-layout-2: Emojis not showing with Xubuntu VM

### ISSUE THREAD

**Issue by khhuang7** [TheOdinProject/css-exercises#474]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Emojis might not show up properly when using Google Chrome in Xubuntu 22.04 with VirtualBox 7.0.14. Note this has previously been [reported by others](https://discord.com/channels/505093832157691914/1071479084535791656/1071479084535791656) who appear not to have found a solution.
<img width="215" alt="flex exercise 07 with no color emojis" src="https://github.com/TheOdinProject/css-exercises/assets/63946129/b6608ccf-e12f-49bf-8833-6c46326011f0">

I'd suggest adding instructions on how to fix this to the exercise, or at least noting that it might happen and it's not an important part of the exercise to resolve it, in case any beginner is confused (or is a perfectionist). I found it was a simple fix, but not necessarily among the first Google results: reinstall the emoji font family. The fix is:
```
$ sudo apt remove fonts-noto-color-emoji
$ sudo apt install fonts-noto-color-emoji
```
or
```
$ sudo apt reinstall fonts-noto-color-emoji
```

**2. How To Reproduce:**

1. Open index.html in Google Chrome in Xubuntu 22.04 with VirtualBox 7.0.14.
2. If the emojis show correctly, run in Terminal:
`$ sudo apt remove fonts-noto-color-emoji`
3. Close Google Chrome applications, then reopen index.html in Google Chrome.

**3. Expected Behavior:**
Emojis show up in color per the desired-outcome images:
<img width="500" alt="flex exercise 07 with expected color emojis" src="https://github.com/TheOdinProject/css-exercises/blob/main/flex/07-flex-layout-2/desired-outcome.png?raw=true">

**4. Desktop/Device:**
-   Device: Lenovo laptop
-   OS: Windows 11 Pro + Virtual Box 7.0.14 with Xubuntu 22.04 installed
-   Browser: Google Chrome v120.0.6099.224

**5. Additional Information:**
Happy to help write the fix into the exercise if desired. It would be helpful to know if there's a preference for this to sit in the README.md hints or commented in the code.

**Comment by thatblindgeye** [comment]
Adding a disclaimer in the README seems like the easiest path. I don't think we should send users to install things just for this exercise, and another alternative is remove the emojis from the exercise, including the imagine in the README.

@khhuang7 I'll assign you to add a disclaimer to the README
