### ISSUE TITLE
03-grouping-selectors README: typo and suggested fixes

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/css-exercises#475]
Originally posted on the [curriculum repo](https://github.com/TheOdinProject/curriculum/issues/27148)

> ### Describe your suggestion
> In the readme.md file for lesson 3 of the CSS exercises (03-grouping-selectors), paragraph 2, the word "instead" is used twice in one sentence. This is redundant. Really, you can tighten up the copy and here's three ways:
>
> Original sentence: "Instead of having a single element with two different rules applied, though, you're instead going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."
>
> Option 1 (smaller fix, deleting the redundant word): "Instead of having a single element with two different rules applied, though, you're going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."
>
> Option 2 (better fix): "For this exercise, you're instead going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."
>
> Option 3 (more complete fix, with my rationale): The first paragraph of this readme covers a coding solution it says we hopefully used, and then tells us that we're not gonna do that here. Really, there's not much value to stating this as whether we pursued that solution or not, you've admitted that it doesn't impact this lesson. So I'd cut down the wording to remove this, which means the first two paragraphs can be joined.
>
> "Let's build a little off the previous exercise. Here, you're going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles."

**Comment by looonnng** [comment]
Hello, I would like to get this assigned as my first contribution. Let me know which option is best as replacement :)

**Comment by MaoShizhong** [comment]
@looonnng Assigned. The 3rd option would be most ideal, in my opinion. This will result in the first two paragraphs of that README being combined into a single one that reads:
> Let's build a little off the previous exercise. Here, you're going to give two elements each a unique class name, then add rules for styles that both elements share as well as their own unique styles. Make sure you take a good look at the outcome image below to see exactly what is unique about each element, and what both elements have in common.

**Comment by looonnng** [comment]
Hi @MaoShizhong, thanks again for the assignment. I had difficulty with this one, since I got quite a few of my exercise solutions in the repo. So, I recloned a whole new repo in another location, and that seems to work. Please let me know if there's any issues.

**Comment by MaoShizhong** [comment]
@looonnng Sounds like you just had local commits muddying up your local `main` branch. No problems on the PR end so looks like you've got that all sorted :)
