### ISSUE TITLE
Bug - Foundations - class-id-selectors: desired outcome and solution do not match.

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/css-exercises#492]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The desired outcome screenshot shows all the elements with the same sans-serif font.  However, the instructions and the solution only instruct to change the odd elements.  Therefore, the even elements should still be serif.

**2. How To Reproduce:**

**3. Expected Behavior:**

<img width="488" alt="Screen Shot 2024-02-17 at 7 36 38 PM" src="https://github.com/TheOdinProject/css-exercises/assets/126961361/35859ded-af45-4c9a-b1a0-0dbf67bea9e2">

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**
As an aside this template feels odd to me.

**Comment by thatblindgeye** [comment]
@fabulousgk assigned!
