### ISSUE TITLE
05-descendant-combinator: outcome can be done without descendants

### ISSUE THREAD

**Issue by prestontiger** [TheOdinProject/css-exercises#499]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

In the current format of this lesson, achieving the desired outcome is possible by targeting either the div types or the .container class without having to use descendant combinator. This approach may inadvertently lead learners to conclude they have successfully completed the task, even if they haven't fully met the intended guidelines.

A potential solution could involve moving the 2nd p type inside the first div type and renaming it's class to nottext or anything that isn't the same class as all the other p types, also changing it to a <span tag, so that it still works with all possible combinations of type and class. 

Even though it seems small, this issue confused me as I was making changes and observing their effects. Without realizing it, I met all the requirements early in the exercise by just targeting a single div, when the lesson aimed to teach about the descendant combinator. Fixing this could really help make learning clearer and prevent similar confusion for others.

Thank you for considering this suggestion.

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by MaoShizhong** [comment]
Closing due to no response, and no further action required.
