### ISSUE TITLE
Block and Inline: <Element defaults not really being mentioned so far in the course>

### ISSUE THREAD

**Issue by spektukal** [TheOdinProject/css-exercises#545]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

I've just gone through the second CSS exercise from the Block and Inline lesson and was confused to no end about where the top margin of the title element came from. The solution shows that you need to add "  margin-top: 0;" to it. But how are we supposed to know this? As far as I'm aware nothing of the sort was ever mentioned anywhere in the course material so far.

After asking for help on Discord, @FireHeart eventually mentioned the CSS Cascade lesson where default values were very briefly mentioned. But only in the context that different browsers can have different default values for elements, leading to unexpected behavior.

To me this looks like an oversight because stuff like this definitely needs to be explained clearly in the lesson where it's relevant. And I've probably wasted more than an hour now on trying to figure it out. And being very confused the whole time about why it hasn't been mentioned anywhere so far. When explaining this in just 1 or 2 lines would have already avoided that. Maybe it's missing because of some changes that were made to the course but I couldn't say.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-block-and-inline

### (Optional) Discord Name

spektukal

### Acceptance Criteria

- [ ] Remove the `margin-top: 0;` style from the solution CSS on the `.title` element
- [ ] Update the screenshot in the README to reflect the above change (the screenshot should show the default margin-top for the "I'm a card" text)

**Comment by CraftreeSolitary** [comment]
@thatblindgeye Do you mind if I work on this? I would love to take this up as my first issue.
