### ISSUE TITLE
04-chaining-selectors: Exercise is solvable without selector chaining.

### ISSUE THREAD

**Issue by ShepleySound** [TheOdinProject/css-exercises#55]
The "original" photos in this exercise have hyphenated class values (original-proportioned/original-distorted).

This makes it so that the exercise is solvable by only selecting the unique classes in the "avatar" photos. There's no need to chain the avatar class, since "proportioned" and "distorted" are not actually shared between the elements.

Solution: Remove hyphens from the second set of photos.

**Comment by duncantop** [comment]
I think I miss the point of this exercise. Why do we even need an avatar class name? I'm new to this, but it feels like avatar should be doing something to transform images, and then proportioned and distorted should make their own modifications. Is defining a "single selector" with chained class names just a normal idiom?

**Comment by thatblindgeye** [comment]
@ShepleySound Thank you for mentioning this, and apologies that it took so long to get back. Would you like to be assigned to fix this issue?

@duncantop The point of the exercise is just to practice chaining selectors.

**Comment by ShepleySound** [comment]
@thatblindgeye Sure, I'd be happy to!

**Comment by thatblindgeye** [comment]
Closed as an update was merged in #77
