### ISSUE TITLE
Bug - : Intro to CSS: desired-outcome.png image does not properly illustrate desired CSS outcome

### ISSUE THREAD

**Issue by depleur** [TheOdinProject/css-exercises#559]
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files.

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
In the [Grouping Selectors](https://github.com/TheOdinProject/css-exercises/tree/main/foundations/03-grouping-selectors) module of the `foundations` folder, the `desired-outcome.png` file (and thus the README.md image) does not correctly convey the bold weight of the first button. 

**2. How To Reproduce:**
1. Clone the repo.
2. Go to the foundations folder.
3. Open the image titled `desired-outcome.png` in the folder `03-grouping-selectors`.
4. Compare the given image with the buttons after the intended CSS is applied to them.

**3. Expected Behavior:**

The first button should look boldened.

**4. Desktop/Device:**

- Device: MacBook Pro (M2 Pro)
- OS: MacOS 14.4 Sonoma
- Browser and Version: Chrome (Version 126.0.6478.57) and Firefox Developer Edition (v128.0b1)

**5. Additional Information:**

Firefox does not show the black borders around the second button either, but that is fixed when browsing on a Chromium based browser, so I'm guessing that is a compatability issue with Gekko and/or Firefox.

**Comment by sdobron-1** [comment]
I do not see this behavior on my machine.

Device: Lenovo X1 Carbon 6th Gen.
OS: Linux Mint 21.3 Cinnamon
Browsers: Firefox 127.0.1, Chromium 126.0.6478.114

Firefox displays the the buttons slightly different, but text is bold and for all intents and purposes of the exercise is accurate. Please share your code as incorrect code would explain the lack of bold text on your end.

![Screenshot from 2024-06-22 19-44-19](https://github.com/TheOdinProject/css-exercises/assets/171972165/c0532b21-50ec-4327-92c3-76c810c04bd1)

**Comment by depleur** [comment]
![desired-outcome](https://github.com/TheOdinProject/css-exercises/assets/89105989/eea25695-dced-43ea-a3d9-4ff5827bc37c)

This is what I meant by the image being a little misleading. For me, the desired-outcome.png file is the one that is wrong. Nothing to do with code.

**Comment by MaoShizhong** [comment]
Funnily enough, #355 had the bold property added because the author believed the image showed bold text for the first element.

When you compare actual bold text, it does not match the image. Therefore, @depleur I'll assign you to undo the changes made by that PR (i.e. remove the bold requirement, and relevant css).

**Comment by depleur** [comment]
@MaoShizhong I've submitted a PR to close this issue.
