### ISSUE TITLE
Bug - 06-flex-layout: desired-outcome.png not matching solution

### ISSUE THREAD

**Issue by mat-95** [TheOdinProject/css-exercises#570]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The desired-outcome image does not match the solution. The space between the logo and the input is larger in the solution than the one shown in the desired-outcome image. This issue was introduced in #360. It was mentioned in the comments of #349, that using gap would produce uneven spacing, but the image was not updated in the PR.

desired-outcome.png:
![desired-outcome](https://github.com/TheOdinProject/css-exercises/assets/98151215/5189a212-2243-420b-b128-328a24725052)

Solution output:
![desired-outcome](https://github.com/TheOdinProject/css-exercises/assets/98151215/149508b4-79b6-430e-874b-14fc8f981329)

**2. How To Reproduce:**

Apply solution.css to index.html file and open it. Compare it with desired-outcome.png.

**3. Expected Behavior:**

The space between the logo and the input should match between the web page and desired-outcome.png.

**4. Desktop/Device:**

-   Device: Laptop
-   OS: Ubuntu 22.04
-   Browser: chrome
-   Version: 126.0.6478.126

**Comment by MaoShizhong** [comment]
Fair spot. Feel free to PR a replacement of the desired outcome image with what the solution code produces.
