### ISSUE TITLE
Documentation - Clarification - css-exercises/margin-and-padding/02-margin-and-padding-2

### ISSUE THREAD

**Issue by akhawasim** [TheOdinProject/css-exercises#588]
Can you clarify that if it is ok to edit the index.html or we strictly only edit the style.css file?

Thank you

**Comment by MaoShizhong** [comment]
While there aren't any instructions stating "you must not touch the html", the aim of that exercise is to change CSS only. You do not need to change the HTML.

Just a note that for clarification/help questions, it would be best to ask in our Discord server as opposed to a repo issue (which are more for reporting bugs or suggesting features etc.)
