### ISSUE TITLE
Bug - Main Directory: Wrong folder name

### ISSUE THREAD

**Issue by BoomTNT29** [TheOdinProject/css-exercises#595]
Complete the following REQUIRED checkboxes:
-   [*] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [*] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The name of the folder is mis-leading:
![image](https://github.com/user-attachments/assets/d9752fac-4622-4013-b5c8-bbb7cc7886c6)

**2. How To Reproduce:**

Navigating to the folder mentioned in the assignment takes a while (https://www.theodinproject.com/lessons/foundations-intro-to-css).

**3. Expected Behavior:**

Name of folder should match.

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by CouchofTomato** [comment]
@BoomTNT29 What do you expect the folder name to be?

**Comment by BoomTNT29** [comment]
I expected it to be "CSS Exercises", because when I first saw it, I got confused by the name "Foundations". But now it makes sense 😅
