### ISSUE TITLE
Bug - :Grid exercises Solution and README.md contradicts each other for 01-responsive-holy-grail 

### ISSUE THREAD

**Issue by devnchill** [TheOdinProject/css-exercises#606]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- Last two points of self checks tells height of header and footer should increase on minimizing the width of overall website.
- Even the screenshots show that thickness increases on minimizing the site using devtools.
- But if use the solution it opposes that behaviour. 
- Thickness is directly proportional to width of website.
- https://discord.com/channels/505093832157691914/505093832157691916/1292840680875622513 
- this talks about it with screenshots and recordings.

**2. How To Reproduce:**

Just use the code of solution and preview it , it will be visible there.

**3. Expected Behavior:**

 I expected the solution to behave like it's mentioned in README.md (thickness perhaps height of header and footer is inversely proportional to width of website)

**4. Desktop/Device:**

-   Device: HP notebook 15.6 inch
-   OS: Arch Linux
-   Browser: chrome,brave
-   Version: 

**5. Additional Information:**

**Comment by MaoShizhong** [comment]
The wording of the checks can definitely be improved for clarity. The "stretch taller" bit is mainly referring to row 3 (the "article" container) due to its p contents. We can just have the checks say that the columns narrow and widen as the viewport changes size, and some rows get taller to accommodate for any text wrapping.

Assigning this to you to reword.
