### ISSUE TITLE
06-cascade-fix: color blindness problem red/green

### ISSUE THREAD

**Issue by Frittenfred97** [TheOdinProject/css-exercises#76]
in the exercise 06-cascade-fix the colors red and green were used, but for people that have colorblindness it is difficult to see the difference. If possible it would be better to use opposite colors like yellow/blue, red/yellow, blue/green.

**Comment by rishvantsingh** [comment]
I would like to work on this issue.

**Comment by Munmun6392** [comment]
Hello @Frittenfred97  I want to work on this. Please assigned it to me.

**Comment by marvingay** [comment]
@rishvantsingh Are you still interested in working on this?
