### ISSUE TITLE
07-flex-layout-2 - adding more information to self-check

### ISSUE THREAD

**Issue by PinkieBarto** [TheOdinProject/css-exercises#88]
Having spent 2 hours debugging an extremely simple fix, I propose adding a single line to self-check section to avoid wasting time for new learners:

- Ensure each card has a width of 300px

**Comment by thatblindgeye** [comment]
@PinkieBarto Would you want to make a PR to add that item to the Self check of the exercise?

**Comment by scheals** [comment]
@thatblindgeye I will gladly take this on if possible :)

**Comment by thatblindgeye** [comment]
@scheals I've assigned you, thank you for taking this on!
