### ISSUE TITLE
"Readme" needs to detail "Fork" process

### ISSUE THREAD

**Issue by joshshark** [TheOdinProject/css-exercises#93]
The Readme for the CSS Exercises [https://github.com/TheOdinProject/css-exercises/blob/main/README.md](url) main folder says to "fork and clone" the Github repository, but the curriculum never explains how to "fork" a repository when we get to this point. 

When following the curriculum and getting to the "Practice" section of "CSS Foundations" lessons [https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/css-foundations](url), we are directed for the first time to "fork" a repository with no prior instructions on HOW to fork.   We are directed to follow a link to TOP Github and to follow the "ReadMe" file.   The "Readme" file says to "fork and clone" the repository.  A link is provided on how to "clone" but now how to "fork".  Two completely different processes.

Some more detailed instructions on how to "fork" to your own repository and clone will be helpful for newbies. 

Thanks

**Comment by SnakeGandhi** [comment]
Created Pull Request that suggests a change. Good eye. I was coming here to post this issue too. (https://github.com/TheOdinProject/css-exercises/pull/95)

**Comment by thatblindgeye** [comment]
Closing this issue as it was resolved in #95 as mentioned above.
