### ISSUE TITLE
flex-04-information

### ISSUE THREAD

**Issue by kiaenOdin** [TheOdinProject/css-exercises#96]
The content of the information blurbs aren't all aligned. Pepper is slightly lower than the other three.
It bothers me, could fixing that be added to the solution?

It's caused by the lack of a third line the that particular one. 

I didn't have the same issue, as I made each blurb it's own flex container, instead of one whole flex container.

**Comment by thatblindgeye** [comment]
@kiaenOdin I believe there is a simpler solution to this, which was also mentioned in #51 . Would you want to make a PR to remove the `align-items: center;` rule from the `.container` block in the `solution.css` file?

This should fix the issue of the Self Check stating to not align things vertically, while also fixing the issue of one item looking lower than the rest (though this may not 100% alleviate that annoyance, as some images might have more white space along the top edge).

**Comment by thatblindgeye** [comment]
Because this is a duplicate issue, I will be closing this. Any further work or discussion on this issue should take place in #51
